
###Get Users
 GET http://localhost:5000/user/all
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7fSwiaWF0IjoxNzAwOTg0NTY4LCJleHAiOjE3MDA5ODQ4Njh9.lGQ50oUTLtVmOnmYFe1W-gs-iXp5q0WvRympmPEJApU

###Get Tasks
 GET http://localhost:5000/task/today
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW00MjVAZ21haWwuY29tIn0sImlhdCI6MTcwMDk4NDg4MCwiZXhwIjoxNzAwOTg1MTgwfQ.5zv1Iw5uZ3T9GgLAdCsxQ5NK6KOdLJeT9IgGTK8-at0

###Get completed/incompleted Tasks 
 GET http://localhost:5000/task/tasks
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW1rYW1saTQyNUBnbWFpbC5jb20ifSwiaWF0IjoxNzAwOTkyMzk5LCJleHAiOjE3MDA5OTI5OTl9.9kC991j6MRBzvqZuT3gHxA8VLJs01dVh283eRwraI9o
###Register User
POST http://localhost:5000/user/add HTTP/1.1
content-type: application/json

{
    "username": "hemk425",
    "email": "hem425@gmail.com",
    "password": "hem@2810"
}



###Login User
POST http://13.200.251.232//user/login HTTP/1.1
content-type: application/json

{
    "email": "hemkamli425@gmail.com",
    "password": "123"
}

###Generate new Access Token
POST http://localhost:5000/user/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW1rYW1saTQyNUBnbWFpbC5jb20ifSwiaWF0IjoxNzAxMDk3MTY3LCJleHAiOjE3MDEwOTgzNjd9.hFsmFHGW2N7TaxuBucwZqxyqKE9n2RYVx_Q6du9xmxc"
}


###Verify User update
GET http://localhost:5000/user/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW1rMkBnbWFpbC5jb20ifSwiaWF0IjoxNzAwMzgyMTk0LCJleHAiOjE3MDAzODIzMTR9.HkOZ_cb-SfgUoeK_tpcj8D2VhiVjMco5aIBQH1RQjLg HTTP/1.1
content-type: application/json



###send OTP
POST http://localhost:5000/user/send-otp HTTP/1.1
content-type: application/json

{
    "email": "hemkamli425@gmail.com"
}

###Compare OTP
POST http://localhost:5000/user/check-otp HTTP/1.1
content-type: application/json

{
    "inputOtp": "4728"
}


###Reset Password
PUT http://localhost:5000/user/reset-password HTTP/1.1
content-type: application/json

{
    "email": "hemkamli425@gmail.com",
    "password": "Hem@28102002"
}


###Add or create a new task
POST http://localhost:5000/task/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW1rYW1saTQyNUBnbWFpbC5jb20ifSwiaWF0IjoxNzAxMTU1OTMxLCJleHAiOjE3MDExNTYyMzF9.vP-vN04KT5afQk_XA_xYR1GucXmI8SFnJefoIPrldBg

{
    "title": "API integratiom",
    "description": "COmplete API intergration for Task Management Project",
    "dueDate": "2023-11-30"
}

###Delete Task
DELETE  http://localhost:5000/task/65545a03c8d9f1c623210a15 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJ0ZXN0dXNlcjEifSwiaWF0IjoxNzAwMDMwMjg3fQ.CHTWlltalBSX2iL5EqDZJdXA4TTLQcEQed3V0VDP-VM


### update task status
PUT  http://localhost:5000/task/status/6563159ce984b9a02329d599 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoZW1rYW1saTQyNUBnbWFpbC5jb20ifSwiaWF0IjoxNzAxMTAwMjk3LCJleHAiOjE3MDExMDAzNTd9.KfTh9-5USWT-j3I4D4Hx0R_Sep9eiCv-fRxEWo_tDSk